- listeners/GPII_USBListener/README.md
- listeners/README.md
- listeners/installer/README.md
* Builds with VS 2012
* Single EXE and no extra DLLs (removed libcurl.dll)
* USB listening now works
* No F11 hotkey to avoid clashes
> Various Bugs for Windows Listeners - support NTAG and Provide installer

- Gruntfile.js
@javihernandez Here is the fix for the windows build.
> GPII-1137:  Remove "grunt start" from source and documentation.

- README.md
- Vagrantfile
- provisioning/build.bat
- provisioning/chocolatey-packages.bat
- provisioning/npm-packages.bat
- provisioning/universal.bat
These changes require an updated Vagrant box used by the GPII CI server:
https://github.com/idi-ops/packer-windows/commit/fe400f04192d9fa1e23547ae82e1f263ff8c441d
> GPII-1814: Fixes CI build

- Vagrantfile
- provisioning/build.bat
- provisioning/chocolatey-packages.bat
- provisioning/universal.bat
These changes switch the Node.js version back to 32-bit and also clean up the build scripts.
> GPII-1826: Switches Node.js to 32-bit version

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- gpii/node_modules/spiSettingsHandler/test/testHighContrastToEmpty.json
- gpii/node_modules/spiSettingsHandler/test/testSpiSettingsHandler.js
GPII-1873: Fixing problem of Windows defining the value of default scheme to null for HighContrast method.
Workaround for the current problem we are having with HighContrast method.
> GPII-1873: Fixing problem of Windows defining the value of default scheme to null for HighContrast method.

- index.js
representing Windows platform for use in Journalling component and other contexts
This pull request partners https://github.com/GPII/universal/pull/463 but does not depend on it
> GPII-580: Added registration of Infusion ContextAwareness marker 

- gpii/node_modules/spiSettingsHandler/src/SpiChildProcess.js
- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- gpii/node_modules/spiSettingsHandler/test/testSpiSettingsHandler.js
Worked around this problem by making the SPI_SETNONCLIENTMETRICS SPI call in a separate process. This will prevent the main process from being blocked.
> GPII-2001: Unit tests get stalled at some point during its execution

- provisioning/Chocolatey.ps1
It's fixed in upstream and we are using fixed versions now so it's not needed we can drop it.
> GPII-2195 : Reverting GPII-1996 (8b02552) because it's not needed anymore.

- gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
As described in GPII-2125, since we can't set the screen resolution to something that is not recognized as valid (VirtualBox does its own black magic when resizing), we at least should try to restore the resolution to the closest valid one.
> GPII-2125: Use the closest available resolution when setting it

- gpii/node_modules/registeredAT/registeredAT.js
Only the settings of the first instance of magnifier are applied. Subsequent instances continue to use those set first.
This fix performs some clean-up that magnifier would have done if it was closed nicely.
> GPII-2315: Magnifier doesn't apply subsequent settings

- gpii/node_modules/processHandling/test/testProcessHandling.js
This problem only happens when running the tests from within electron, more info at https://issues.gpii.net/browse/GPII-2302
> GPII-2302: Replace calls to shelljs.exec

- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
Magnifier deletes a registry key before GPII does.
I just made it ignore the error if trying to delete a registry key that doesn't exist - as long as the key doesn't exist at the end, then does it matter wasn't there to being with?
> GPII-2339: Unable to log out if magnifier is closed manually

- Vagrantfile
- provisioning/Chocolatey.ps1
This way, we avoid hardcoding the path to a particular version of Wix.
> GPII-2438: Get the path to the current version of wixtoolset

- gpii/node_modules/spiSettingsHandler/test/testAPI.json
- gpii/node_modules/spiSettingsHandler/test/testMouse.json
- listeners/GPII_RFIDListener/README.md
- listeners/GPII_RFIDListener/include/FlowManager.h
- listeners/GPII_RFIDListener/src/Diagnostic.cpp
- listeners/GPII_RFIDListener/src/FlowManager.cpp
- listeners/GPII_RFIDListener/src/GPII_RFIDListener.cpp
- listeners/GPII_RFIDListener/src/GPII_RFIDListener.rc
- package.json
The fixes to work with https://github.com/GPII/universal/pull/513 which take the "logged in/out" state out of the RFID listener.
However, "logout" is still sent when the listener is closed (or the reader has gone).
> GPII-2402: Replaced "login" and "logout" with "proximityTrigger"

- gpii/node_modules/windowsMetrics/src/windowsMetrics.js
This prevents the metrics capture starting while testing.
> GPII-2582: Fix failure in gpii-app tests

- gpii/node_modules/processReporter/dotNetProcesses.csx
- gpii/node_modules/processReporter/processesBridge.js
- gpii/node_modules/processReporter/test/processReporterModuleTests.js
- gpii/node_modules/processReporter/test/processesBridge_tests.js
- package.json
@amb26 @stegru As noted in [PR 47](https://github.com/GPII/universal/pull/547), this fixes a mistyped `{arguments}.0` in the windows processes bridge code (among other minor improvements).
Looking for a process by Id or name takes about 30 - 35 msec on my VM.
> GPII-442:  Fixed typo in arguments list.

- gpii/node_modules/processReporter/dotNetProcesses.csx
- gpii/node_modules/processReporter/test/processesBridge_tests.js
@javihernandez, here's a pull request to fix the unit test in gpii-app. 
The problem: when run under PowerShell, the C# code returns slightly different information compared to when run under the older command prompt.  CI for the windows repo uses the command prompt for the unit tests (and they all pass).  Gpii-app, however, is launched via a PowerShell script, and the difference causes that one unit test to fail.  I've normalized the output of the C# code such that it should no longer matter.
I hope this does the trick.
> Fix processes bridge to run the same in PowerShell as in Command Prompt

- gpii/node_modules/processReporter/dotNetProcesses.csx
- gpii/node_modules/processReporter/processesBridge.js
- package.json
@javihernandez @amb26 @stegru Here's a fix.
I ended up testing the npm module `string-argv` using the problematic command line that Javi listed in the [GPII-2613](https://issues.gpii.net/browse/GPII-2613)'s description, and it had no problem.  I've removed the C# makeArgv() code, and moved the functionality to JavaScript, introducing a dependency on `string-argv`.
In the process (no pun intended) I noticed that getting the command name of the process and the full path to the executable was done independently of creating the argv[].  However, removing the argv[] has implications for the universal code, and given Sandra's timeline (this needs to work by Mon), this was the way I went.
Have a look, and let me know what you think.
> GPII-2613 Process reporter tests failures

- gpii/node_modules/processReporter/dotNetProcesses.csx
Modified the C# ("dotNetProcesses.csx") to handle the exception where the process has exited while fetching information about it, specifically its process ID.
> GPII-2668:  Windows Process Reporter: C# "process not running" exception

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
Added null characters to values read and written to the registry.
See [GPII-2751](https://issues.gpii.net/browse/GPII-2751?focusedCommentId=29806&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-29806).
> GPII-2751: Gibberish from the registry

- gpii/node_modules/windowMessages/src/windowMessages.js
- index.js
> GPII-3066: Stop acceptance tests crashing

- gpii/node_modules/registeredAT/registeredAT.js
Fixes intermittent failures in the acceptance tests.
Like https://github.com/GPII/windows/pull/167#issuecomment-400005673
> GPII-3140: Made enableRegisteredAT.set return a promise

- gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
- gpii/node_modules/displaySettingsHandler/src/dpiWindows10.js
- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
Fixes the DPI setting so it works as expected with hidpi displays.
The DPIScale is now the offset from the recommended value.
Testing:
You'll need a display whose recommended DPI setting is above 100%. See https://issues.gpii.net/browse/GPII-3230 for how to do it on a VM. The `salem` preference set should make the scale 1 value above the recommended, and the Larger snap-sets (like `snapset_1b`) should make things larger.
> GPII-3230: Made DPIScale relative to the recommended setting.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
When changing the DPI scale or screen resolution, the cursor is moved to the centre of the screen (this does not happen in a virtual machine, because the host owns the pointer).
(M3: https://docs.google.com/document/d/1NODvtQA6YKRdIsIDSLP-gqcnN6nTkxg8cqlPoNCGTDQ/edit)
This fix moves the mouse cursor back to the physical position before the screen change. That is, if you put your finger on the mouse pointer before changing the DPI/resolution, the pointer should remain under your finger (if your finger moves, there may be medication to prevent this).
**How to test**
* If running in a VM, uncheck *Mouse integration* from the *Input* menu (after making sure you know the key used to release the mouse - usually right ctrl). This is to allow the guest to move the mouse pointer.
* For testing the …
> GPII-3371: Restoring cursor position back to the physical position before resolution/DPI change.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/windowsMetrics/README.md
- gpii/node_modules/windowsMetrics/src/windowsMetrics.js
- gpii/node_modules/windowsMetrics/test/WindowsMetricsTests.js
This adds the following new metrics:
* System info (CPU, Memory, display, windows version)
* GPII versions
* Mouse wheel
* A README file
* The ability to disable mouse/key metrics (eg, if anti-virus complains, or it's too much data).
Updates the following:
* Window activation:
* logged when it happens, removed duration active (which can be implied).
* Added window identifier.
* Using WM_SHELLHOOK notification, rather than polling.
* Modifier key state during key/mouse input.
(no changes to universal)
> GPII-3349: Metrics improvements

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- gpii/node_modules/spiSettingsHandler/test/testSpiSettingsHandler.js
- package.json
To test:
* Change the wallpaper
* Key-in with high-contrast (`snapset_2a`)
* Wallpaper goes
* Key-out
* The wallpaper should be the same as what it was before key-in (before this fix, it was the default wallpaper).
Requires https://github.com/GPII/universal/pull/710
> GPII-2618: Restoring wallpaper after high contrast.

- gpii/node_modules/processHandling/processHandling.js
- gpii/node_modules/windowsMetrics/src/windowsMetrics.js
When changing the language and high-contrast at the same time, the wallpaper and colours sometimes did not get applied, or where half applied.
It might be best to wait for https://github.com/GPII/windows/pull/217.
This change makes it wait until the high-contrast has finished doing its thing before restarting explorer.
To test:
- Key in with a different language and high-contrast (`226722c6-8895-40b4-9297-424b9da9c340`, I think)
- The desktop should be black, colours correct for high-contrast.
- Key out
- Desktop wallpaper should return, and colours applied correctly.
> GPII-3501: Fix high-contrast + language combination

- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
This should fix one of the failures in GPII-3528, by waiting for the resolution to change before testing the DPI.
Unfortunately, it's another one of those random/timing issues which depend on the wind direction.
```
15:53:25.832:  jq: FAIL: Module "Windows Display Settings Handler Tests" Test name "Testing setScreenDpi " - Message: setScreenDpi -1
15:53:25.832: jq: Expected: { "actual": -1, "configured": -1, "minimum": 0, "maximum": 1 }
15:53:25.832: jq: Actual: { "configured": -1, "minimum": 0, "maximum": 0, "actual": -1 } 
```
> GPII-3543: Waiting for resolution to be applied before testing DPI.

- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
I think the problem was that the ANSI version of GetExplicitEntriesFromAcl was being used, instead of the unicode one - or at least, changing it stops the crash.
There is another fix where some buffers allocated just 1 byte for a boolean. This caused a couple of buffer overruns, but no crash.
> NOJIRA: Fix crash in tests when running with electron

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
The pointer was being freed, rather than the memory it points to.
Testing in https://github.com/GPII/gpii-app/pull/72
> Fixes test crash in electron

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
When setting a high-contrast theme while high-contrast is already on, the current theme was being saved.
This fix makes only the current theme be saved it it's not high-contrast, so the custom wallpaper is restored correctly.
https://github.com/GPII/universal/pull/724 can be ignored.
> GPII-2618: Not saving the current theme if it's a high-contrast one.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/processHandling/processHandling.js
- gpii/node_modules/processHandling/test/testProcessHandling.js
- gpii/node_modules/windowMessages/src/windowMessages.js
This should fix the issue where *explorer* is showing a mixture of languages. It ensures that all folder windows are also closed (they should also re-appear).
> GPII-3558: Closing explorer folder windows when restarting explorer.

- gpii/node_modules/gpii-localisation/src/language.js
- gpii/node_modules/gpii-localisation/test/testLanguage.js
Corrects the casing of language codes, so `en-gb` becomes `en-GB`.
> GPII-3605: Correcting language code casing

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/WindowsUtilities/test/WindowsUtilitiesTests.js
- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
Back-end for the open usb button, which performs the following:
- If a single USB Drive is found, then that gets opened.
- If there's more than 1, then all drives that don't have a gpii token file are opened. (if all drives have a token then all are opened)
A "USB Drive" is a fixed or removal volume on the USB bus (which isn't a CD-ROM or Ramdisk).
Used by https://github.com/GPII/gpii-app/pull/92
> GPII-3739: Open USB folder.

- gpii/node_modules/WindowsUtilities/test/WindowsUtilitiesTests.js
Sorting the result array before assertion.
The array is built asynchronously, so the order isn't guaranteed (nor does it matter).
> GPII-3807: getUserUsbDrives test failure.

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
Still unsure of the underlying cause, but here's a workaround.
After the theme has been applied, this fix just reads the .theme file and manually applies the colours.
Works well with https://github.com/GPII/universal/pull/761
> GPII-3811: Make custom high-contrast themes work with updated Windows.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
This fixes the usb task tray icon not being able to eject the usb drive, after opening it with GPII.
(most of the change is re-indentation for a try-catch block)
> GPII-3739: Closing the handle to the usb device after finishing with it.

- gpii/node_modules/processHandling/processHandling.js
This patch was suggested by @stegru to improve the order of promise resolution that guarantees a proper explorer shutdown.
> GPII-3866: Explorer wont restart in certain timing conditions

- gpii/node_modules/gpii-office/README.md
- gpii/node_modules/gpii-office/index.js
- gpii/node_modules/gpii-office/package.json
- gpii/node_modules/gpii-office/src/reset.xml
- gpii/node_modules/gpii-office/src/ribbon.js
- gpii/node_modules/gpii-office/src/ribbonReload.cs
- gpii/node_modules/gpii-office/test/ribbonTest.js
- index.js
- package.json
- tests/UnitTests.js
This contains the code to update the ribbon on Office applications.
@Karadaliev, I've made enough progress on the office simplification for you to start working with it. At the moment, it only performs the file swapping and doesn't restart Word.
If you point your reference of gpii-windows to this branch, `stegru/windows#GPII-3927`, it will pull in the branch of universal I'm working on.
I'm guessing this will be implemented in a similar way that the high-contrast or screen-scale widgets speak with core, the preference is `http://registry\.gpii\.net/applications/com\.microsoft.office` (the final `.` is not escaped).
The values can be one of the following, depending on the checkbox values:
`StandardSet`
`Basics+StandardSet`
`Essentials+StandardSet`
`Basics+Essentials+StandardSet`
(if that's …
> GPII-3927: Office simplification

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/processHandling/processHandling.js
- gpii/node_modules/processHandling/test/test-window.cs
- gpii/node_modules/processHandling/test/testProcessHandling.js
This provides `gpii.windows.startProcess`, which can start a new process with the instruction to set the initial window to a given state of minimised, maximised, inactive, or hidden.
Not every application honours this. With Chrome in particular, it only works if there is not already a chrome instance running. I might update this branch to work around it, if feasible.
It's equivalent to the *Run* option in the executable's property dialog:
> GPII-4079: Start a process while specifying the initial window state.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/gpii-userInput/README.md
- gpii/node_modules/gpii-userInput/index.js
- gpii/node_modules/gpii-userInput/src/sendKeys.js
- gpii/node_modules/gpii-userInput/test/manualSendKeys.js
- gpii/node_modules/gpii-userInput/test/testSendKeys.js
- index.js
- tests/UnitTests.js
@Karadaliev:
This provides the back-end implementation of the "Make your own button" feature.
The entry point to this is `gpii.windows.sendKeys.send`, and it accepts a string that's closely similar to that of AutoHotKey's [Send command](https://www.autohotkey.com/docs/commands/Send.htm).
> GPII-4135: Send keys implementation

- gpii-service/tests/processHandling-tests.js
- provisioning/NpmInstall.ps1
More asserts where being run than expected.
Perhaps due to the `close` event of a `ChildProcess` being raised more than once - perhaps for each standard io stream?  Let's see if the more appropriate `exit` event is better.
> GPII-4353: Using 'exit' event of process, instead of 'close'.

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- provisioning/NpmInstall.ps1
Fixes the fault found in AJC3 where the high-contrast setting wasn't being restored.
To test: Unset `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes@CurrentTheme`, it should still work.
> GPII-4343: Saving the default theme if the current theme is unknown.

- gpii/node_modules/gpii-app-zoom/test/testAppZoom.js
- gpii/node_modules/gpii-localisation/src/language.js
- gpii/node_modules/gpii-localisation/src/languageNames.js
- gpii/node_modules/gpii-localisation/test/testLanguage.js
- gpii/node_modules/gpii-userInput/test/testSendKeys.js
- gpii/node_modules/gpii-windowManagement/test/appBarTests.js
- gpii/node_modules/nativeSettingsHandler/test/testNativeSettingsHandler.js
- gpii/node_modules/systemSettingsHandler/test/testSystemSettingsHandler.js
- package.json
Improved the error reporting in the language tests.
Also stopped gpii from being started by fixing the main script in `package.json` and removing the `%gpii-windows` requires from the tests (they're harmless, but not needed).
> GPII-4365: Language test improvements

- provisioning/NpmInstall.ps1
And updated according to the currently installed version of the .Net
framework in the windows vagrant box (2020.02.11)
> GPII-4367: Re-added the frameworkPathOverride to NpmInstall.ps1

- gpii/node_modules/systemSettingsHandler/src/systemSettingsHandler.js
This stops Morphic from stalling and preventing the logout/shutdown of Windows.
> GPII-4370: Rejecting settings handler if the settings helper fails.

- gpii-service/tests/all-tests.js
- provisioning/NpmInstall.ps1
This will stop the `gpii-service` build from taking things from `/node_modules`, to using its own `node_modules` instead.
> NOJIRA: Building the service in its own isolated drive.

- index.js
- package.json
Fixes a problem where the Office ribbon wasn't being downloaded (`SELF_SIGNED_CERT_IN_CHAIN`).
This was due to it being run behind an invasive https proxy, and node using a hard-coded list of CA certificates, rather than those provided by the OS.
This fix instructs node to use the Windows certificate store, which means certificates that the administrator has added are also trusted. In other words, if it works in the browser it will work with node.
Unsure why https connections to the gpii cloud still worked, however.
*To reproduce:*
* Get the root certificate for `untrusted-root.badssl.com`, and add it to the *Trusted Root Certifications Authorities* certificate store. (remove it after)
* In [win32.json](https://github.com/GPII/universal/blob/master/testData/solutions/win32.json5#L16132-L16 …
> GPII-4186: Using windows certificate store for certificates.

- gpii/node_modules/gpii-app-zoom/src/appZoom.js
This just updates an environment variable, so a new child process knows the active window before the QSS was clicked.
This is so the select to speech app (which will be called by a BYOB) knows what window to read the selected text from.
> GPII-4470: Storing the currently active window in an environment variable
