- provisioning/build.bat
https://issues.gpii.net/browse/GPII-2003
> GPII-2003: Use different vcbuildtools for different build artifacts

- provisioning/Chocolatey.ps1
Fixing typo, -version to --version calling Chocolatey install.
> GPII-2130 : Fixing typo, -version to --version.

- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
https://issues.gpii.net/browse/GPII-2148
> GPII-2148 Removing unused debugging blocks.

- gpii/node_modules/registeredAT/registeredAT.js
- gpii/node_modules/registeredAT/test/testRegisteredAT.js
Small change to stop the "deactivate AT" routine from being delayed.
> GPII-2073: Persona Settings return on windows lock screen (again)

- provisioning/Chocolatey.ps1
Now we have available all the nodejs and npm environment vars in the first execution of the VM.
> GPII-2277 : Executing nodevars.bat correctly in PS1 environment.

- gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
- provisioning/Build.ps1
- provisioning/Tests.ps1
This pr is meant to land hst-2017, not master (yet). @gloob just confirm that this is what you were asking for. @kaspermarkus once we have an ok from @gloob, can you review/merge this?
> GPII-2287: Moved build of test-window.c into Tests.ps1

- package.json
There's currently a problem with ref 1.3.5.
https://github.com/TooTallNate/ref/issues/86
> NOJIRA: Using ref 1.3.4

- gpii/node_modules/processReporter/processesBridge.js
- package.json
Also, updated universal reference
> GPII-2084: Use electron-edge when running on electron

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/windowsMetrics/src/windowsMetrics.js
- gpii/node_modules/windowsMetrics/test/WindowsMetricsTests.js
- package.json
Improvements:
- Mouse activity.
- Inactivity detection.
- Solution IDs that are applied.
- Keystroke times logged better
- Only capturing metrics when keyed in
- Error reporting contains the stack
- Unit tests are a lot better
> GPII-2583: Metrics improvements

- gpii.js
- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/displaySettingsHandler/src/displaySettingsHandler.js
- gpii/node_modules/displaySettingsHandler/src/dpiWindows10.js
- gpii/node_modules/displaySettingsHandler/src/dpiWindows8.js
- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
- gpii/node_modules/processHandling/processHandling.js
- gpii/node_modules/processHandling/test/testProcessHandling.js
- gpii/node_modules/processReporter/processReporter.js
- gpii/node_modules/processReporter/processesBridge.js
- gpii/node_modules/processReporter/test/all-tests.js
- gpii/node_modules/processReporter/test/processReporterModuleTests.js
- gpii/node_modules/processReporter/test/processesBridge_tests.js
- gpii/node_modules/registeredAT/registeredAT.js
- gpii/node_modules/registeredAT/test/testRegisteredAT.js
- gpii/node_modules/registryResolver/index.js
- gpii/node_modules/registryResolver/src/RegistryResolver.js
- gpii/node_modules/registryResolver/test/testRegistryResolver.js
- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- gpii/node_modules/spiSettingsHandler/test/testSpiSettingsHandler.js
- gpii/node_modules/windowsMetrics/test/WindowsMetricsTests.js
- index.js
- package.json
- tests/AcceptanceTests.js
Works with https://github.com/GPII/universal/pull/548
> GPII-2568: Updated references to universal with gpii-universal

- gpii/node_modules/displaySettingsHandler/src/dpiWindows10.js
- gpii/node_modules/displaySettingsHandler/test/testDisplaySettingsHandler.js
This adds the ability to know the minimum DPI value (in addition to the maximum and current).
> GPII-3370: Retrieving the minimum DPI value.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/gpii-localisation/README.md
- gpii/node_modules/gpii-localisation/index.js
- gpii/node_modules/gpii-localisation/src/language.js
- gpii/node_modules/gpii-localisation/test/testLanguage.js
- gpii/node_modules/processHandling/processHandling.js
- gpii/node_modules/registrySettingsHandler/src/RegistrySettingsHandler.js
- gpii/node_modules/registrySettingsHandler/test/testRegistrySettingsHandler.js
- index.js
- tests/UnitTests.js
The detection of languages installed on the OS.
> GPII-3544: Get installed languages.

- gpii/node_modules/registeredAT/test/testRegisteredAT.js
This might* fix the test failure of narrator not starting, when it obviously did.
It now waits for narrator to start... fails after 10 seconds.
*I can't reproduce it.
>  GPII-3303: Waiting for narrator to start.

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- package.json
Made https://github.com/GPII/windows/pull/234/files even better.
Commented + added null check
> GPII-2618: Improved #234

- Vagrantfile
- package.json
- provisioning/CouchDB.ps1
See https://issues.gpii.net/browse/GPII-3744
> GPII-3744: Added provisioning script to install and setup CouchDB

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/nativeSettingsHandler/src/nativeSettingsHandler.js
- package.json
**Warning: Not merge yet**
This PR may be subject to future changes.
> GPII-3722: Provide support for Mouse Qs Button

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/processHandling/processHandling.js
- package.json
**Warning: Not merge**
The pull request covers at this point a 93% of Read&Write settings.
> GPII-3652: Onboard new version of Read&Write

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/gpii-windowManagement/README.md
- gpii/node_modules/gpii-windowManagement/index.js
- gpii/node_modules/gpii-windowManagement/src/appBar.js
- gpii/node_modules/gpii-windowManagement/test/appBarTests.js
- index.js
- tests/UnitTests.js
The windows side of https://github.com/GPII/gpii-app/pull/176
> GPII-4289: Make the QuickStrip "docked" to the taskbar.

- gpii/node_modules/spiSettingsHandler/src/SpiSettingsHandler.js
- package.json
This merge is only to demonstrate the viability of another pull as an upstream dependency.  It should not be merged.
See [the associated universal pull for details](https://github.com/GPII/universal/pull/852) for details.
cc: @amb26
> GPII-4382: Updated to use universal branch to test work in progress.

- gpii/node_modules/wmiSettingsHandler/src/WmiSettingsHandler.js
- gpii/node_modules/wmiSettingsHandler/test/testWmiSettingsHandler.js
See https://issues.gpii.net/browse/GPII-4033
> GPII-4033: Removed language constraints when dealing with wmi queries

- gpii/node_modules/gpii-userInput/README.md
Fixing a small typo in the send keys readme.
> NOJIRA: Fixed typo

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/WindowsUtilities/test/WindowsUtilitiesTests.js
A better fix than https://github.com/GPII/windows/pull/255
> GPII-3830: Detect if a drive exists before opening it.

- gpii/node_modules/WindowsUtilities/WindowsUtilities.js
- gpii/node_modules/windowsMetrics/src/windowsMetrics.js
- gpii/node_modules/windowsMetrics/test/WindowsMetricsTests.js
> GPII-4208: Fixed metrics interaction with eTests using Windows RAW API
